#!/bin/bash
#SBATCH --job-name=TMMC_0.0001k
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 24:00:00
#SBATCH --mem 6GB
#SBATCH -p main
#SBATCH --export=ALL
#SBATCH --output=ar.out
#SBATCH --error=ar.err

#export RASPA_DIR=${HOME}/RASPA/simulations/

#$RASPA_DIR/bin/simulate $1

#/home/sp1709/src_gauge_cell/src_gauge_cell
#/home/sp1709/RASPA2_GC-TMMC/src/simulate 
#/home/sp1709/RASPA2_with_cyl_pore/src/simulate
/home/sp1709/src_gauge_cell/RASPA_gauge_cell/src_gauge_cell/src_gauge_cell
